name: testIfConditions

on:
  push:
  workflow_dispatch:
        
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: start
        id: str
        run: |
          echo "start"
          echo "${{ job.status }}"
          echo "${{ github.event.inputs }}"
          echo "::save-state name=state::${{ job.status }}"
        shell: bash
        
      - name: check
        if: ${{ steps.str.outputs.state == 'success' }}
        run: |
          echo "working!"
          echo "${{ job.status }}"
        shell: bash
          
  test2:
    runs-on: ubuntu-latest
    needs: test1
    steps:
      - name: trigger
        if: ${{ steps.str.outputs.state == 'success' }}
        id: trg
        run: |
          echo "yeah!"
          echo "${{ job }}"
        shell: bash
        
