name: testIfConditions

on:
  push:
  workflow_dispatch:
        
jobs:
  test1:
    id: tst
    runs-on: ubuntu-latest
    steps:
      - name: start
        id: str
        run: |
          echo "start"
          var1="${{ job.status }}"
          echo "${{ github.event.inputs.* }}"
          echo "::save-state name=state::$var1"
          #echo "::set-output name=state::success"
        shell: bash
        
      - name: check
        if: ${{ steps.str.outputs.state == 'success' }}
        run: |
          echo "working!"
          echo "${{ job.status }}"
        shell: bash
          
      - name: trigger1
        if: ${{ steps.str.outputs.state == 'success' }}
        id: trg1
        run: |
          echo "yeah!"
          echo "${{ job }}"
        shell: bash
        
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: trigger2
        if: ${{ jobs.tst.steps.str.outputs.state == 'success' }}
        id: trg
        run: |
          echo "yeah!"
          echo "${{ job }}"
        shell: bash
        
