name: testIfConditions

on:
  push:
  workflow_dispatch:
        
jobs:
  test1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.str.outputs.state }}
    steps:
      - name: start
        id: str
        run: |
          echo "start"
          var1="${{ job.status }}"
          echo "state=$var1" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: check
        if: ${{ steps.str.outputs.state == 'success' }}
        run: |
          echo "working!"
          echo "${{ job.status }}"
        shell: bash
          
      - name: trigger1
        if: ${{ steps.str.outputs.state == 'success' }}
        id: trg1
        run: |
          echo "yeah!"
          echo "${{ job }}"
        shell: bash
        
  test2:
    runs-on: ubuntu-latest
    needs: test1
    steps:
      - name: trigger2
        if: ${{ needs.test1.outputs.output1 == 'success' }}
        id: trg
        run: |
          echo "yeah!"
        shell: bash
        
